load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "parse",
    srcs = ["caching.go"],
    importpath = "github.com/foursquare/scala-gazelle/parse",
    visibility = ["//visibility:public"],
)
